trainset: gta5
valset: cityscapes

model:
    pretrained: True
    bn_backbone:  freezed_bn
    bn_aspp: bn
    bn_decoder: bn 

data:
    target:
        name: cityscapes
        rootpath: dataset/CityScape
        split: train
        img_rows: 1024
        img_cols: 2048
        batch_size: 1
        img_norm: True
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        n_class: 19
        num_workers: 1
    n_class: 19
    